# Generated by Django 4.1.1 on 2022-10-03 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('datetime_todo', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('tags', models.ManyToManyField(to='todos.tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user_id'], name='todos_todo_user_id_1cf07d_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['active'], name='todos_todo_active_9ef397_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['datetime_todo'], name='todos_todo_datetim_d1d362_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user_id'], name='todos_tag_user_id_0b7aad_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='todos_tag_name_3f3d94_idx'),
        ),
    ]
