# Generated by Django 4.1.1 on 2022-10-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datetime_todo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(null=True, to='todos.tag'),
        ),
    ]
