# Generated by Django 4.1.1 on 2022-10-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todos.tag'),
        ),
    ]
