# Generated by Django 4.1.1 on 2022-10-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_todo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datetime_todo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
